name: Publish to NuGet.org

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore src/SteamApis.Net/SteamApis.Net.csproj

    - name: Build
      run: dotnet build src/SteamApis.Net/SteamApis.Net.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack src/SteamApis.Net/SteamApis.Net.csproj --configuration Release --no-build --output ./nupkg

    - name: Push to nuget.org
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
